ecommerce/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('category', views.category_list, name='category'),
    path('product', views.product_list, name='product'),
    path('banner-details/<slug>', views.banner_details, name='banner-details'),
    path('user/login', views.user_login, name='user-login'),
    path('user/register', views.user_register, name='user-register'),

    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ecommerce.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Settings(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='logo/', blank=True, null=True)
    favicon = models.ImageField(upload_to='favicon/', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Setting'

    def __str__(self):
        return self.name


class Banner(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    subtitle = models.CharField(max_length=100)
    image = models.ImageField(upload_to='banner/')
    description = RichTextField()

    class Meta:
        verbose_name_plural = 'Banner'

    def __str__(self):
        return self.title

    def get_limit_description(self):
        return self.description[:100]


class Category(models.Model):
    cat_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.cat_name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='product/')
    description = RichTextField()
    stock = models.IntegerField(default=0)
    quantity = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = 'Product'

    def __str__(self):
        return self.product_name

    def get_limit_description(self):
        return self.description[:100]

ecommerce/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


def index(request):
    data = {
        'bannerData': Banner.objects.all(),
        'categoryData': Category.objects.all(),
        'productData': Product.objects.order_by('-id'),
    }
    return render(request, 'pages/home/index.html', data)


def contact(request):
    return render(request, 'pages/contact/contact.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user_data = authenticate(username=username, password=password)
        if user_data:
            login(request, user_data)
            return redirect('index')
        else:
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        return render(request, 'pages/user/login.html')


def user_register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user_data = User.objects.create(username=username, email=email, password=password)
        login(request, user_data)
        return redirect('index')
    else:
        return render(request, 'pages/user/register.html')


def category_list(request):
    data = {
        'categoryData': Category.objects.all(),
    }
    return render(request, 'pages/category/category.html', data)


def product_list(request):
    data = {
        'productData': Product.objects.all(),
    }
    return render(request, 'pages/product/product.html', data)


def banner_details(request, slug):
    data = {
        'bannerData': Banner.objects.get(slug=slug),
    }
    return render(request, 'pages/banner/banner-details.html', data)


@login_required(login_url="/users/login")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("index")


@login_required(login_url="/users/login")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_detail(request):
    return render(request, 'pages/cart/index.html')

templates/layouts/footer.html
{% load static %}
<footer id="footer"><!--Footer-->


		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left"></p>
					<p class="pull-right">Designed by <span><a target="_blank" href="{% url 'index' %}">Estore</a></span></p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->




    <script src="{%  static 'js/jquery.js' %}"></script>
	<script src="{%  static 'js/bootstrap.min.js' %}"></script>
	<script src="{%  static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{%  static 'js/price-range.js' %}"></script>
    <script src="{%  static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{%  static 'js/main.js' %}"></script>
</body>
</html>

templates/layouts/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    {% if settingData.favicon %}
        <link rel="icon" href="{{ settingData.favicon.url }}">
    {% endif %}
</head><!--/head-->

<body>
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> {{ settingData.phone }}</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> {{ settingData.email }}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        {% if settingData.logo %}
                            <a href="{% url 'index' %}"><img src="{{ settingData.logo.url }}" alt=""/></a>
                        {% endif %}
                    </div>

                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'user-register' %}"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="#"><i class="fa fa-crosshairs"></i> Checkout</a></li>
                            <li><a href="{% url 'cart_detail' %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                            <li><a href="{% url 'user-login' %}"><i class="fa fa-lock"></i> Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="{% url 'index' %}" class="active">Home</a></li>
                            <li><a href="{% url 'category' %}">Category</a></li>
                            <li><a href="{% url 'product' %}">Product</a></li>
                            <li><a href="{% url 'contact' %}">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/master/master.html
{% include 'layouts/header.html' %}

{% block content %}
{% endblock %}

{% include 'layouts/footer.html' %}

templates/pages/banner/banner-details.html
{% extends "master/master.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><a href="{% url 'index' %}">Home</a> /Banner Details</h1>
            </div>
            <div class="col-md-12">
                <h1><a href="">{{ bannerData.title }}</a></h1>
                {% if bannerData.image %}
                    <img src="{{ bannerData.image.url }}" class="img-responsive" alt="">
                {% endif %}
                <p>
                    {{ bannerData.description |safe }}
                </p>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/cart/index.html
{% extends "master/master.html" %}
{% load cart_tag %}
{% block content %}
    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="#">Home</a></li>
                    <li class="active">Shopping Cart</li>
                </ol>
            </div>
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for key,value in request.session.cart.items %}
                    <tr>
                        <td class="cart_product">
                            <a href=""><img src="{{value.image}}" style="width: 60px;" alt=""></a>
                        </td>
                        <td class="cart_description">
                            <h4><a href="">{{value.name}}  </a></h4>

                        </td>
                        <td class="cart_price">
                            <p>{{value.price}}</p>
                        </td>
                        <td class="cart_quantity">
                            <div class="cart_quantity_button">
                                <a class="cart_quantity_up"
                                   href="{% url 'item_increment' value.product_id %}"> + </a>
                                <input class="cart_quantity_input" type="text" name="quantity" value="{{value.quantity}}"
                                       autocomplete="off" size="2">
                                <a class="cart_quantity_down"
                                   href="{% url 'item_decrement' value.product_id %}"> - </a>
                            </div>
                        </td>
                        <td class="cart_total">
                            <p class="cart_total_price">
                                {{ value.price|multiply:value.quantity }}
                            </p>
                        </td>
                        <td class="cart_delete">
                            <a class="cart_quantity_delete" href="{% url 'item_clear' value.product_id %}"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section> <!--/#cart_items-->

{% endblock %}

templates/pages/category/category.html
{% extends "master/master.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Category List</h1>
            </div>
        </div>
        {% for category in categoryData %}
            <div class="row">
                <div class="col-md-12">
                    <h1><a href="">{{ category.cat_name }}</a></h1>
                </div>
                <div class="col-md-12">
                    {% for product in category.product_set.all %}
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        {% if product.image %}
                                            <img src="{{ product.image.url }}" alt=""/>
                                        {% endif %}
                                        <h2>Rs: {{ product.price }}</h2>
                                        <p>{{ product.product_name }}n</p>
                                        <a href="#" class="btn btn-default add-to-cart"><i
                                                class="fa fa-shopping-cart"></i>Add
                                            to cart</a>
                                    </div>
                                    <div class="product-overlay">
                                        <div class="overlay-content">
                                            <h2>{{ product.price }}</h2>
                                            <p>{{ product.product_name }}</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i
                                                    class="fa fa-shopping-cart"></i>Add to cart</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="choose">
                                    <ul class="nav nav-pills nav-justified">
                                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/pages/contact/contact.html
{% extends "master/master.html" %}
{% block content %}

    <h1>Contact page</h1>


{% endblock %}

templates/pages/home/index.html
{% extends "master/master.html" %}
{% block content %}
    <section id="slider"><!--slider-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="slider-carousel" class="carousel slide" data-ride="carousel">

                        <div class="carousel-inner">
                            {% for banner in bannerData %}
                                {% if forloop.counter == 1 %}
                                    <div class="item active">
                                        <div class="col-sm-6">
                                            <h1><span>{{ banner.title }}</span></h1>
                                            <h2>{{ banner.subtitle }}</h2>
                                            <p>
                                                {{ banner.get_limit_description |safe }}
                                            </p>
                                            <a href="{% url 'banner-details' banner.slug %}"
                                               class="btn btn-default get">Get it now</a>
                                        </div>
                                        <div class="col-sm-6">
                                            <img src="{{ banner.image.url }}" class="girl img-responsive" alt=""/>
                                            <img src="{{ banner.image.url }}" class="pricing" alt=""/>
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="item">
                                    <div class="col-sm-6">
                                        <h1><span>{{ banner.title }}</span></h1>
                                        <h2>{{ banner.subtitle }}</h2>
                                        <p>
                                            {{ banner.get_limit_description |safe }}
                                        </p>
                                        <a href="{% url 'banner-details' banner.slug %}" class="btn btn-default get">Get it now</a>
                                    </div>
                                    <div class="col-sm-6">
                                        <img src="{{ banner.image.url }}" class="girl img-responsive" alt=""/>
                                        <img src="{{ banner.image.url }}" class="pricing" alt=""/>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>

                        <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </section><!--/slider-->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>Category</h2>
                        <div class="panel-group category-products" id="accordian">
                            {% for category in categoryData %}
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title"><a href="#">{{ category.cat_name }}</a></h4>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>

                    </div>
                </div>

                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->
                        <h2 class="title text-center">Product List</h2>
                        {% for product in productData %}
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            {% if product.image %}
                                                <img src="{{ product.image.url }}" alt=""/>
                                            {% endif %}
                                            <h2>Rs: {{ product.price }}</h2>
                                            <p>{{ product.product_name }}n</p>
                                            <a href="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i
                                                    class="fa fa-shopping-cart"></i>Add
                                                to cart</a>
                                        </div>
                                        <div class="product-overlay">
                                            <div class="overlay-content">
                                                <h2>{{ product.price }}</h2>
                                                <p>{{ product.product_name }}</p>
                                                <a href="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i
                                                        class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="choose">
                                        <ul class="nav nav-pills nav-justified">
                                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div><!--features_items-->

                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/pages/product/product.html
{% extends "master/master.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Product List</h1>
            </div>
        </div>

        <div class="col-md-12">
            {% for product in productData %}
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}" alt=""/>
                                {% endif %}
                                <h2>Rs: {{ product.price }}</h2>
                                <p>{{ product.product_name }}n</p>
                                <a href="#" class="btn btn-default add-to-cart"><i
                                        class="fa fa-shopping-cart"></i>Add
                                    to cart</a>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <h2>{{ product.price }}</h2>
                                    <p>{{ product.product_name }}</p>
                                    <a href="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i
                                            class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>



{% endblock %}

templates/pages/user/login.html
{% extends "master/master.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Login Page</h1>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                  <div class="form-group">
                      <label for="name">name</label>
                      <input type="text" id="name" class="form-control" required name="username">
                  </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" class="form-control"
                               required name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/user/register.html
{% extends "master/master.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Register Page</h1>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">name</label>
                        <input type="text" id="name" class="form-control" required name="username">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" class="form-control" required name="email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" class="form-control"
                               required name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}